language: python

python:
  - '3.5'

install:
  - pip install .

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
      branch: master
